In [1]:
import numpy as np

In [9]:
a = np.arange(25)

a.shape, a.dtype, a.size, a.itemsize

((25,), dtype('int32'), 25, 4)

#### Strides
- 다음 메모리로 갈 때 필요한 메모리

In [10]:
a.strides

(4,)

In [12]:
b = a.reshape(5,5)
b.strides # 행을 넘길 때 20 / 열을 넘길 떄 4

(20, 4)

In [23]:
b.sum(), b.sum(axis = 1), b.sum(axis = 0)

(300, array([ 10,  35,  60,  85, 110]), array([50, 55, 60, 65, 70]))

In [25]:
# reduce 개념으로 이루어 졌다. => 초기값 지정 가능
b.sum(initial = 10) 

310

#### Broad Casting

In [33]:
a = np.array([1,2,3])
b = np.array([1,2,3]).reshape(3,1)

a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

#### Universe function

In [34]:
type(np.add)

numpy.ufunc

In [35]:
np.add(3,4), np.add([2,3],[4,5,])

(7, array([6, 8]))

In [49]:
# np.lookfor('sum') # sum이 들어간 모든 함수
# np.lookfor('*') # numpy에서 지원하는 모든 함수
# np.info(np.abs) # Shift + Tab 과 동일 기능

### SciPy

In [37]:
import scipy

In [53]:
a = np.arange(1000, dtype=np.float64)
b = np.arange(1000)
c = np.arange(1000, dtype=np.float16)

In [51]:
%timeit a*a

991 ns ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [52]:
%timeit b*b

1.5 µs ± 9.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [55]:
%timeit c*c

6.33 µs ± 322 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [59]:
# np.sctypeDict # type 관련 단축어
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [60]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [70]:
a = np.array([1,2,3])
b = np.asfarray(a)
# c = np.frombuffer
a.astype('i8'), a.astype(np.int64), b

(array([1, 2, 3], dtype=int64),
 array([1, 2, 3], dtype=int64),
 array([1., 2., 3.]))

#### Structured Array

In [100]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [101]:
x['age'], x[['age']] # x.age : error

(array([9, 3]), array([(9,), (3,)],
       dtype={'names':['age'], 'formats':['<i4'], 'offsets':[40], 'itemsize':48}))

#### Record Array

In [102]:
x = np.rec.array([(1, 2., 'Hello'), (2, 3., "World")],
                 dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])

In [104]:
x.foo, x['foo'], x[['foo']] # pandas와 동일 기능

(array([1, 2]), array([1, 2]), rec.array([(1,), (2,)],
           dtype={'names':['foo'], 'formats':['<i4'], 'offsets':[0], 'itemsize':18}))

#### Shape

In [109]:
a = np.arange(25)
a.reshape(5,5) # return이 있기 때문에 immutable 방식

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
a.resize(5,6, refcheck=False) # return이 없기 때문에 mutable 방식

a # zero padding

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24,  0,  0,  0,  0,  0]])

#### Split

In [122]:
x = np.arange(25).reshape(5,5)
y = np.arange(24).reshape(4,6)

In [143]:
np.vsplit(x, (2,3)) # hsplit

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [145]:
np.split(x, (2,3)) # axis

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

#### Stack, Concatenate, r_, c_

In [147]:
a, b = np.vsplit(y, 2)

In [153]:
np.stack([a,b]) # 차원 증가

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [154]:
np.vstack([a,b])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [156]:
np.hstack([a,b])

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [159]:
np.concatenate([a,b])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [161]:
np.r_[a, b] 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [162]:
np.c_[a, b] 

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

#### Source 보는 방법

In [165]:
from sklearn.model_selection import train_test_split

import inspect

# print(inspect.getsource(train_test_split))

## 딥러닝 개론