## Tensorflow

#### Tensor vs Numpy
- GPU 가능
- immutable
- 용어의 정리

In [31]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.1.0'

In [8]:
# tensorflow 상수
# 개별 재할당 불가
a = tf.constant([1,2,3])

In [32]:
a, a + a, type(a), np.add(a,a)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>,
 tensorflow.python.framework.ops.EagerTensor,
 array([2, 4, 6]))

In [29]:
# 변수
b = tf.Variable([1,2,3])

# dir(b) # assign 존재
b.assign_add([1,2,3])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 4, 6])>

In [35]:
# numpy to tensor
# resource가 많이 든다.
c = np.array([1,2,3])

tf.add(c,c)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

In [46]:
from tensorflow.keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [48]:
X_train.shape, X_train.dtype

((60000, 28, 28), dtype('uint8'))

In [51]:
# record 별 사용가능
tf.data.Dataset.from_tensor_slices(X_train)

<TensorSliceDataset shapes: (28, 28), types: tf.uint8>

In [52]:
# 전체를 한 묶음으로 사용
tf.data.Dataset.from_tensors(X_train)

<TensorDataset shapes: (60000, 28, 28), types: tf.uint8>

In [57]:
# 원하는 개수만큼 데이터 추출
s = tf.data.Dataset.from_tensor_slices(X_train)
ss = iter(s)

# next(ss)
s.take(1)

<TakeDataset shapes: (28, 28), types: tf.uint8>

#### 실제 예제

In [109]:
# Hold out
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train / 255
X_test = X_test / 255

# 간단하게 만들때 사용
model = tf.keras.models.Sequential

# 상속 또는 Functional API 이용할 떄 사용
model1 = tf.keras.models.Model

issubclass(model,model1)

True

In [110]:
model = tf.keras.models.Sequential([
    # 처음 layer에는 데이터 하나의 shape을 지정해주어야 한다.
    # 2차원이 아닌 1차원으로 넣어야 한다.
    # Flatten 사용하면 1차원으로 만들어준다.
    # 참고) 모델링할때는 미리 1차원으로 만드는 것을 지향 => Simple is the Best
    tf.keras.layers.Flatten(input_shape = (28,28)), 
    # tf.keras.layers.Dense(64, input_shape=(28*28,)), 
    tf.keras.layers.Dense(64), 
    # name 변경 가능
    tf.keras.layers.Dense(10, name = 'output')
], name = 'moon')

model.summary()

Model: "moon"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_5 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_16 (Dense)             (None, 64)                50240     
_________________________________________________________________
output (Dense)               (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [111]:
# weights / bias 변경 가능
model.layers[1].weights

[<tf.Variable 'dense_16/kernel:0' shape=(784, 64) dtype=float32, numpy=
 array([[ 0.06961875,  0.01953642, -0.0647839 , ...,  0.06908327,
         -0.06342509,  0.01634805],
        [-0.02453556,  0.03362995,  0.05971267, ..., -0.06931063,
          0.01214379, -0.04357231],
        [ 0.00752649, -0.00545548, -0.08193938, ...,  0.00738433,
         -0.06151353,  0.07363781],
        ...,
        [ 0.0522906 , -0.02017499, -0.07522655, ...,  0.04117396,
         -0.07008968,  0.05588596],
        [-0.0641247 ,  0.07414315,  0.04056626, ...,  0.02650893,
         -0.00245689, -0.00319421],
        [ 0.00128315, -0.0075996 , -0.04967219, ...,  0.01422485,
          0.00263991,  0.01445448]], dtype=float32)>,
 <tf.Variable 'dense_16/bias:0' shape=(64,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [112]:
model.compile(loss='sparse_categorical_crossentropy',
             optimizer = 'adam',
             metrics = ['accuracy'])

In [113]:
model.fit(X_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 42us/sample - loss: 2.3542 - accuracy: 0.3139
Epoch 2/5
60000/60000 [==============================] - 2s 31us/sample - loss: 2.3029 - accuracy: 0.2027
Epoch 3/5
60000/60000 [==============================] - 2s 36us/sample - loss: 2.3026 - accuracy: 0.2038
Epoch 4/5
60000/60000 [==============================] - 3s 44us/sample - loss: 2.3026 - accuracy: 0.2038
Epoch 5/5
60000/60000 [==============================] - 2s 37us/sample - loss: 2.3026 - accuracy: 0.2038


In [99]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 30us/sample - loss: 2.3026 - accuracy: 0.5809


[2.3025851249694824, 0.5809]

## NLP